Style/HashSyntax:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*

# Most rspec blocks are long
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/**/* # Most config blocks are long
    - config/routes.rb # this doesn't work - and I don't know why
