# fly.toml file generated for gcsd-poc on 2023-04-10T00:12:23+01:00

app = "gcsd-poc"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"

[env]
  PORT = 8080
  RAILS_ENV = "production"

[mounts]
  source="gcsd_data"
  destination="/fly_storage"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
