# Copy of fly.toml app configuration file which was generated for 
# gcsd-poc-staging on 2024-06-10T20:52:54+01:00
# But this one is for production, (so is slightly different)
# Check git history for how it looked originally - it was quite different
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'gcsd-poc'
primary_region = 'lhr'
console_command = '/rails/bin/rails console'

[env]
  BUCKET_NAME = 'gcsd-poc' # CdeB not sure if this is actually required
  RAILS_ENV = 'production'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
