test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# A Fly volume (hard to clone and keep in sync with each other)
fly:
  service: Disk
  root: <%= Rails.root.join("/fly_storage") %>

# A free (up to 5GB S3 compatible) storage service
filebase:
  service: S3
  endpoint: <%= ENV.fetch('FILEBASE_ENDPOINT', nil) %>
  access_key_id: <%= ENV.fetch('FILEBASE_ACCESS_KEY_ID', nil) %>
  secret_access_key: <%= ENV.fetch('FILEBASE_SECRET_ACCESS_KEY', nil) %>
  bucket: <%= ENV.fetch('FILEBASE_BUCKET', nil) %>
  region: <%= ENV.fetch('FILEBASE_REGION', nil) %>
